[tool.poetry]
name = "weaverbird"
version = "0.1.0"
description = "Pandas engine for weaverbird data pipelines"
authors = ["Toucan Toco <dev+weaverbird@toucantoco.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
